/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:48:54 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.nio.CharBuffer;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import java.util.UnknownFormatConversionException;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpAppendable_ESTest extends HelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      textHelpAppendable0.appendTitle(stringBuffer0);
      assertEquals(74, TextHelpAppendable.DEFAULT_WIDTH);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      Stack<List<String>> stack0 = new Stack<List<String>>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(stack0);
      TableDefinition tableDefinition0 = TableDefinition.from("LEFT", linkedList0, linkedList1, linkedHashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      assertEquals(1, textHelpAppendable0.getLeftPad());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendHeader(7, "LEFT");
      assertEquals(3, textHelpAppendable0.getIndent());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[3];
      textHelpAppendable0.appendFormat("IUm", objectArray0);
      assertEquals(3, TextHelpAppendable.DEFAULT_INDENT);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      textHelpAppendable0.appendParagraph(stringBuffer0);
      assertEquals(74, TextHelpAppendable.DEFAULT_WIDTH);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringWriter0);
      Stack<CharSequence> stack0 = new Stack<CharSequence>();
      textHelpAppendable0.appendList(true, stack0);
      assertEquals(10, stack0.capacity());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraphFormat("", (Object[]) null);
      assertEquals(74, TextHelpAppendable.DEFAULT_WIDTH);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 7, 1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(charBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      charBuffer0.flip();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("`jk>~HS2t]b1]E9GJ");
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintWriter0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle("`jk>~HS2t]b1]E9GJ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[9];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setIndent((-2));
      Object[] objectArray0 = new Object[3];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("6Uz138v#p7JUa m", objectArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(0, "LEFT");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      Object[] objectArray0 = new Object[8];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat("Converter must not be null", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MockFile mockFile0 = new MockFile("b\"Qw'YW[T,\"y;Rz7", "b\"Qw'YW[T,\"y;Rz7");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintWriter0);
      Object[] objectArray0 = new Object[2];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("XnIN]%YZrI", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = 'Y'
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }
}
