/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:37:35 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(1739);
      Util.indexOfNonWhitespace(charBuffer0, 50);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Util.ltrim(" s>f%R!Sit2");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Util.indexOfNonWhitespace("s>f%R!Sit2", 12);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Util.defaultValue((String) null, "[6.1");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Util.rtrim((String) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Util.repeatSpace(0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Util.repeat(2242, 'C');
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Util.repeat(0, ']');
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Util.isWhitespace(' ');
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Util.isWhitespace('d');
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Util.isEmpty((CharSequence) null);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Util.isEmpty("@fG");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Util.indexOfNonWhitespace("1h<Ahs#yoX|8jVl8E9", 0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Util.defaultValue("", "");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.repeatSpace((-2840));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.repeat((-1), 'o');
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = Util.repeatSpace(5466);
      Util.rtrim(string0);
      // Undeclared exception!
      Util.ltrim(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace("J:L5eLCu", (-2975));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      char[] charArray0 = new char[9];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace(charBuffer0, (-2936));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = Util.rtrim("MB");
      assertEquals("MB", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = Util.ltrim("                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String string0 = Util.ltrim("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CharBuffer charBuffer0 = Util.defaultValue((CharBuffer) null, (CharBuffer) null);
      assertNull(charBuffer0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String string0 = Util.defaultValue("MB", "");
      assertEquals("MB", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String string0 = Util.repeatSpace(5122);
      Util.rtrim(string0);
      // Undeclared exception!
      Util.rtrim(string0);
  }
}
