/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:36:13 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.PipedWriter;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.TreeSet;
import java.util.Vector;
import java.util.function.Function;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.HelpAppendable;
import org.apache.commons.cli.help.HelpFormatter;
import org.apache.commons.cli.help.OptionFormatter;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractHelpFormatter_ESTest extends AbstractHelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setOptionGroupSeparator((String) null);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Option option0 = new Option("arg", true, "arg");
      OptionGroup optionGroup0 = new OptionGroup();
      Option option1 = new Option((String) null, "Cannot add value, list full.", false, "");
      optionGroup0.addOption(option1);
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("[-arg <arg>--Cannot add value, list full.]", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setSyntaxPrefix("38yovFq");
      List<Option> list0 = helpFormatter0.sort((Iterable<Option>) null);
      helpFormatter0.printHelp("cmdLineSyntax not provided", "cmdLineSyntax not provided", (Iterable<Option>) list0, "{R1~4-N`", false);
      assertEquals("38yovFq", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setSyntaxPrefix("38yovFq");
      Options options0 = new Options();
      helpFormatter0.printHelp("{R1~4-N`", " ", options0, "b86KR|w2p\"#)AW)", true);
      assertEquals("38yovFq", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      String string0 = helpFormatter_Builder0.getOptionGroupSeparator();
      assertEquals(" | ", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      OptionFormatter.Builder optionFormatter_Builder0 = helpFormatter_Builder0.getOptionFormatBuilder();
      assertNotNull(optionFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      TextHelpAppendable textHelpAppendable0 = (TextHelpAppendable)helpFormatter_Builder0.getHelpAppendable();
      assertEquals(74, textHelpAppendable0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.asThis();
      assertSame(helpFormatter_Builder0, helpFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.toSyntaxOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Vector<Option> vector0 = new Vector<Option>(0);
      Option option0 = new Option("arg", true, "arg");
      vector0.add(option0);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(org.apache.commons.cli.Option.class));
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0, function0);
      assertEquals("[-arg <arg>]", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Vector<Option> vector0 = new Vector<Option>();
      Option option0 = new Option("cY", "Xd", true, "Xd");
      vector0.add(option0);
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0);
      assertEquals("[-cY <arg>]", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      OptionFormatter.Builder optionFormatter_Builder0 = OptionFormatter.builder();
      optionFormatter_Builder0.setArgumentNameDelimiters("", "");
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      String string0 = helpFormatter0.toArgName("");
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.addOption((String) null, "");
      helpFormatter0.sort(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Vector<Option> vector0 = new Vector<Option>();
      Option option0 = new Option("cY", "Xd", true, "Xd");
      vector0.add(option0);
      helpFormatter0.sort((Iterable<Option>) vector0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      
      helpFormatter0.setSyntaxPrefix("");
      helpFormatter0.getSyntaxPrefix();
      assertEquals("", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setOptionGroupSeparator((String) null);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Option option0 = new Option("cY", "Xd", true, "Xd");
      option0.setRequired(true);
      helpFormatter0.getOptionFormatter(option0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((OptionGroup) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      arrayList0.add((Option) null);
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Iterable<Option>) arrayList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.OptionFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>();
      Option option0 = new Option((String) null, "usage: ");
      arrayDeque0.add(option0);
      LinkedList<Option> linkedList0 = new LinkedList<Option>(arrayDeque0);
      linkedList0.push(option0);
      // Undeclared exception!
      try { 
        helpFormatter0.sort((Iterable<Option>) linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Options options0 = new Options();
      Collection<Option> collection0 = options0.getOptions();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(collection0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      PriorityQueue<List<String>> priorityQueue1 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition1 = TableDefinition.from("usage: ", list0, linkedList0, priorityQueue1);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(tableDefinition1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TreeSet<Option> treeSet0 = new TreeSet<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      Vector<String> vector0 = new Vector<String>();
      TableDefinition tableDefinition1 = TableDefinition.from("usage: ", list0, vector0, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(tableDefinition1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Iterable<Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TextHelpAppendable textHelpAppendable0 = (TextHelpAppendable)helpFormatter0.getSerializer();
      textHelpAppendable0.setIndent((-1188));
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(" | ", " | ", options0, "%6X%[IF!#Wb-", true);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("EAQJiDd", "", (Iterable<Option>) null, " | ", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Collection<Option> collection0 = options0.getOptions();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "", (Iterable<Option>) collection0, ";G,g}>*", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      helpFormatter0.toSyntaxOptions(optionGroup0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      arrayList0.add((Option) null);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(org.apache.commons.cli.Option.class));
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Iterable<Option>) arrayList0, function0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.OptionFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp("%s %s", (String) null, options0, "", false);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(" | ", (String) null, (Options) null, (String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(priorityQueue0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      helpFormatter0.printOptions(tableDefinition0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Option option0 = new Option("arg", true, "arg");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setRequired(true);
      optionGroup0.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("-arg <arg>", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Vector<Option> vector0 = new Vector<Option>();
      OptionGroup optionGroup0 = new OptionGroup();
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0, optionGroup0).when(function0).apply(any(org.apache.commons.cli.Option.class));
      Option option0 = new Option("cY", "cY", true, "cY");
      vector0.add(option0);
      vector0.addElement(option0);
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) vector0, function0);
      assertEquals("", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("B0", "usage: ", false, "=iW:{");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      Options options1 = options0.addOptionGroup(optionGroup1);
      String string0 = helpFormatter0.toSyntaxOptions(options1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("[-B0]", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      List<Option> list0 = helpFormatter0.sort((Options) null);
      helpFormatter0.printOptions((Iterable<Option>) list0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TreeSet<Option> treeSet0 = new TreeSet<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      helpFormatter0.printHelp(" | ", "", (Iterable<Option>) treeSet0, "usage: ", true);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "", options0, "{R1~4-N`", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionFormatter.Builder optionFormatter_Builder0 = helpFormatter0.getOptionFormatBuilder();
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionFormatBuilder((OptionFormatter.Builder) null);
      assertSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      PipedWriter pipedWriter0 = new PipedWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(pipedWriter0);
      helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      try { 
        helpFormatter0.printOptions(options0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setHelpAppendable((HelpAppendable) null);
      assertSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.toArgName("4~srGfW}wkzE");
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("<4~srGfW}wkzE>", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertEquals("usage: ", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals(" | ", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getComparator();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) treeSet0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter0.getHelpAppendable();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Option option0 = new Option("cY", "cY", true, "cY");
      helpFormatter0.getOptionFormatter(option0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Comparator<Option> comparator0 = helpFormatter_Builder0.getComparator();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setComparator(comparator0);
      assertSame(helpFormatter_Builder0, helpFormatter_Builder1);
  }
}
