/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:50:14 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("CDI*]]s3IK?", linkedList0, stack0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, (List<String>) null, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(1);
      TableDefinition tableDefinition0 = TableDefinition.from("f0aL-)", linkedList0, arrayList0, linkedHashSet0);
      List<String> list0 = tableDefinition0.headers();
      assertFalse(list0.contains("f0aL-)"));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>();
      stack0.setSize(16);
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, stack0, arrayDeque0);
      List<String> list0 = tableDefinition0.headers();
      assertEquals(16, list0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>(969, (Comparator<? super List<String>>) null);
      TableDefinition tableDefinition0 = TableDefinition.from("Mk-u]e6@kQ@G&MrK0", (List<TextStyle>) null, stack0, priorityQueue0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, stack0, linkedList0, linkedList1);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", stack0, linkedList0, linkedList1);
      String string0 = tableDefinition0.caption();
      assertEquals("org.apache.commons.cli.help.TableDefinition$1", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, linkedList0, linkedList1);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, linkedList0, linkedList1);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, linkedList0, linkedList1);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertEquals(0, list0.size());
  }
}
