/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:27:26 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs((-2540));
      option_Builder1.longOpt("oFW3");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.requiresArg();
      assertFalse(boolean0);
      assertEquals((-2540), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option option0 = new Option((String) null, false, "h?plOkFJ_");
      option0.setArgs((-295));
      boolean boolean0 = option0.hasArg();
      assertEquals((-295), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator('f');
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required(true);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "NO_ARGS_ALLOWED");
      option0.setValueSeparator('O');
      option0.setArgs(25);
      option0.processValue("NO_ARGS_ALLOWED");
      assertEquals('O', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      option0.isValuesEmpty();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option option0 = new Option("gczk5", "3e+u_9", true, "=zZ=7l$wt8iq97/8=(k");
      option0.processValue("=zZ=7l$wt8iq97/8=(k");
      boolean boolean0 = option0.isValuesEmpty();
      assertEquals("=zZ=7l$wt8iq97/8=(k", option0.getDescription());
      assertFalse(option0.hasValueSeparator());
      assertEquals("3e+u_9", option0.getLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", false, "");
      option0.setOptionalArg(true);
      option0.hasOptionalArg();
      assertEquals((-1), option0.getArgs());
      assertEquals("", option0.getDescription());
      assertEquals("NO_ARGS_ALLOWED", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.numberOfArgs(16);
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.ParseException");
      option0.getValuesList();
      assertFalse(option0.hasValueSeparator());
      assertEquals(16, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "thGp~,;\"wC{l6;");
      option0.setValueSeparator('4');
      char char0 = option0.getValueSeparator();
      assertEquals('4', char0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option option0 = new Option("NO_ARGSC_ALLOWED", "NO_ARGSC_ALLOWED", true, "thGp~,;\"wC{l6;");
      option0.setValueSeparator('F');
      char char0 = option0.getValueSeparator();
      assertEquals('F', char0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("Q");
      Option option0 = option_Builder0.get();
      option0.getValue((String) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      String string0 = option0.getValue("");
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option option0 = new Option("NO_ARGSC_ALLOWED", "NO_ARGSC_ALLOWED", true, "thGp~,;\"wC{l6;");
      option0.processValue("thGp~,;\"wC{l6;");
      String string0 = option0.getValue();
      assertEquals("NO_ARGSC_ALLOWED", option0.getLongOpt());
      assertEquals("thGp~,;\"wC{l6;", option0.getDescription());
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      option_Builder0.since("Either opt or longOpt must be specified");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since("");
      Option.Builder option_Builder1 = option_Builder0.longOpt("oFW3");
      Option option0 = option_Builder1.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option option0 = new Option("NO_ARGSC_ALLOWED", "NO_ARGSC_ALLOWED", true, "thGp~,;\"wC{l6;");
      option0.getOpt();
      assertEquals("NO_ARGSC_ALLOWED", option0.getLongOpt());
      assertEquals("thGp~,;\"wC{l6;", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option option0 = new Option((String) null, false, "h?plOkFJ_");
      String string0 = option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option option0 = new Option((String) null, true, ";WrQ{.[T[y1VaqL(:0(");
      String string0 = option0.getKey();
      assertNull(string0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      String string0 = option0.getDescription();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option option0 = new Option("Js", (String) null);
      option0.setDescription("");
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder0.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option option0 = new Option((String) null, true, "-7L] <8T`");
      option0.setArgs(0);
      int int0 = option0.getArgs();
      assertFalse(option0.hasArg());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, "Z7[sVdg#r");
      int int0 = option0.getArgs();
      assertEquals("Z7[sVdg#r", option0.getDescription());
      assertEquals(1, int0);
      assertTrue(option0.hasLongOpt());
      assertEquals("", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option option0 = new Option("P5", "P5", false, "org.apache.commons.cli.Converter");
      option0.setArgName("org.apache.commons.cli.Converter");
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
      assertEquals("org.apache.commons.cli.Converter", option0.getDescription());
      assertEquals("P5", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option option0 = new Option("Js", (String) null);
      option0.setArgName("");
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgs(63);
      boolean boolean0 = option0.acceptsArg();
      assertEquals(63, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option("NO_RGS_ALLOWED", "NO_RGS_ALLOWED", true, "thGp~,;\"wC{l6;");
      option0.processValue("thGp~,;\"wC{l6;");
      boolean boolean0 = option0.acceptsArg();
      assertFalse(boolean0);
      assertEquals("NO_RGS_ALLOWED", option0.getLongOpt());
      assertFalse(option0.hasValueSeparator());
      assertEquals("thGp~,;\"wC{l6;", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option("AOE16E", false, "AOE16E");
      // Undeclared exception!
      try { 
        option0.setType((Object) "gM_QEI:?q");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "NO_ARGS_ALLOWED");
      option0.processValue("NO_ARGS_ALLOWED");
      try { 
        option0.getValue((int) 'O');
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 79, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "NO_ARGS_ALLOWED");
      option0.processValue("NO_ARGS_ALLOWED");
      try { 
        option0.getValue((-884));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("org.apache.commons.cli.TypeHandler");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'org.apache.commons.cli.TypeHandler' contains an illegal character : '.'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("a^n$ %z:Tk+Fj8", true, "a^n$ %z:Tk+Fj8");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'a^n$ %z:Tk+Fj8' contains an illegal character : '^'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", "", true, "fWnqr4Ilk4HG");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("DX<hfE-yilh&dkQz", "DX<hfE-yilh&dkQz");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'DX<hfE-yilh&dkQz' contains an illegal character : '<'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder0.get();
      option0.isDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      option_Builder0.longOpt("oFW3");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.isDeprecated();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option option0 = new Option("o5nfyM", "o5nfyM");
      boolean boolean0 = option0.hasValueSeparator();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option("N7HfN", true, "N7HfN");
      option0.setValueSeparator('f');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('f', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgs(63);
      boolean boolean0 = option0.hasArgs();
      assertEquals(63, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      boolean boolean0 = option0.hasArgs();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      boolean boolean0 = option0.hasArg();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option("N7HfN", true, "N7HfN");
      option0.hasArg();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
      assertTrue(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option option0 = new Option("TW", true, "TW");
      option0.getValue();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option option0 = new Option("N7HfN", true, "N7HfN");
      assertTrue(option0.hasArg());
      
      option0.processValue("");
      String string0 = option0.getValue();
      assertFalse(option0.hasLongOpt());
      assertFalse(option0.hasValueSeparator());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option option0 = new Option("TW", true, "TW");
      option0.getKey();
      assertEquals(1, option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option option0 = new Option("NO_ARGSC_ALLOWED", "NO_ARGSC_ALLOWED", true, "thGp~,;\"wC{l6;");
      option0.getValueSeparator();
      assertEquals("thGp~,;\"wC{l6;", option0.getDescription());
      assertEquals("NO_ARGSC_ALLOWED", option0.getLongOpt());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      option0.hasOptionalArg();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      Class<String> class0 = String.class;
      option0.setType(class0);
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option option0 = new Option("N7HfN", true, "N7HfN");
      String string0 = option0.toString();
      assertEquals("[ Option N7HfN [ARG] :: N7HfN :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder0.get();
      option0.setLongOpt("[ Option z Deprecated :: null :: class java.lang.String ]");
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option 'z''[ Option z Deprecated :: null :: class java.lang.String ]': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      String string0 = option0.toDeprecatedString();
      assertEquals("", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option 'z': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("gczk5");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      option0.processValue("gczk5");
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArg());
      assertEquals((-2), option0.getArgs());
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("gczk5");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.requiresArg();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option("N7HfN", true, "N7HfN");
      boolean boolean0 = option0.requiresArg();
      assertTrue(boolean0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "NO_ARGS_ALLOWED");
      option0.setValueSeparator('O');
      option0.processValue("NO_ARGS_ALLOWED");
      // Undeclared exception!
      try { 
        option0.processValue("NO_ARGS_ALLOWED");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      Option option0 = option_Builder0.get();
      // Undeclared exception!
      try { 
        option0.processValue("z");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.deprecated();
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      String string0 = option0.toString();
      assertEquals("[ Option null org.apache.commons.cli.ParseException Deprecated :: null :: class java.lang.String ]", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option option0 = new Option("NO_ARGSC_ALLOWED", "NO_ARGSC_ALLOWED", true, "NO_ARGSC_ALLOWED");
      boolean boolean0 = option0.hasLongOpt();
      assertTrue(boolean0);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      boolean boolean0 = option0.hasLongOpt();
      assertEquals(1, option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      assertFalse(option0.isDeprecated());
      
      String string0 = option0.toString();
      assertEquals("[ Option null org.apache.commons.cli.ParseException[ARG...] :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option("4h", "4h");
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option("N7HfN", true, "N7HfN");
      option0.setArgName("N7HfN");
      boolean boolean0 = option0.hasArgName();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option("4h", "v8?8(:Q%/A^JvB;$L");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertEquals("v8?8(:Q%/A^JvB;$L", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String[] stringArray0 = option0.getValues();
      assertNull(stringArray0);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.numberOfArgs(16);
      option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder0.get();
      option0.processValue("org.apache.commons.cli.ParseException");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasValueSeparator());
      assertEquals(16, option0.getArgs());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("oFW3");
      Option option0 = option_Builder0.get();
      option0.getValue((-2540));
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.numberOfArgs(16);
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.ParseException");
      String string0 = option0.getValue(0);
      assertFalse(option0.hasValueSeparator());
      assertEquals(16, option0.getArgs());
      assertTrue(option0.hasArg());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option option0 = new Option("N7HfN", false, "N7HfN");
      String string0 = option0.getValue("N7HfN");
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.numberOfArgs(16);
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.ParseException");
      String string0 = option0.getValue("");
      assertFalse(option0.hasValueSeparator());
      assertEquals("org.apache.commons.cli.ParseException", string0);
      assertEquals(16, option0.getArgs());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option option0 = new Option("4h", (String) null);
      int int0 = option0.getId();
      assertEquals(52, int0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option option0 = new Option((String) null, false, "6;[8O[)hT");
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setConverter(converter0);
      Converter<?, ?> converter1 = option0.getConverter();
      assertNotNull(converter1);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option("4h", "v8?8(:Q%/A^JvB;$L");
      Option option1 = new Option((String) null, "v8?8(:Q%/A^JvB;$L");
      boolean boolean0 = option0.equals(option1);
      assertEquals("v8?8(:Q%/A^JvB;$L", option0.getDescription());
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option option0 = new Option("4h", "4h");
      Option option1 = new Option("4h", "4h");
      option0.setLongOpt("4h");
      boolean boolean0 = option0.equals(option1);
      assertFalse(option1.equals((Object)option0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option option0 = new Option("4h", (String) null);
      boolean boolean0 = option0.equals(option0);
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.equals(option_Builder0);
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option option0 = new Option("NO_ARGSC_ALLOWED", "NO_ARGSC_ALLOWED", true, "NO_ARGSC_ALLOWED");
      option0.setOptionalArg(true);
      option0.setArgs(0);
      assertTrue(option0.hasOptionalArg());
      
      option0.processValue("NO_ARGSC_ALLOWED");
      assertFalse(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      option_Builder1.longOpt(" ]");
      Option option0 = option_Builder1.get();
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.getOpt();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "NO_ARGS_ALLOWED");
      option0.getType();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("NO_ARGS_ALLOWED");
      Option option0 = option_Builder1.get();
      // Undeclared exception!
      try { 
        option0.addValue("NO_ARGS_ALLOWED");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "NO_ARGS_ALLOWED", true, "NO_ARGS_ALLOWED");
      option0.hashCode();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt(" ]");
      Option option0 = option_Builder0.get();
      option0.isRequired();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.getDescription();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("z");
      Option option0 = option_Builder0.get();
      int int0 = option0.getArgs();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("NO_ARGS_ALLOWED");
      Option option0 = option_Builder0.get();
      option0.clearValues();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option option0 = new Option("4h", (String) null);
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      option_Builder1.numberOfArgs(16);
      Option.Builder option_Builder2 = option_Builder1.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder2.get();
      option0.processValue("org.apache.commons.cli.ParseException");
      assertEquals('=', option0.getValueSeparator());
      assertEquals("org.apache.commons.cli.ParseException", option0.getValue());
      assertTrue(option0.hasArg());
      assertEquals(16, option0.getArgs());
      assertTrue(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option option0 = new Option("4h", (String) null);
      Option option1 = (Option)option0.clone();
      boolean boolean0 = option0.equals(option1);
      assertFalse(option1.hasLongOpt());
      assertNotSame(option1, option0);
      assertTrue(boolean0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("NO_ARGS_ALLOWED");
      Option option0 = option_Builder1.get();
      option0.getValuesList();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setRequired(true);
      assertTrue(option0.isRequired());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setOptionalArg(true);
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasOptionalArg());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.getArgName();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Class<Option> class0 = Option.class;
      Option.Builder option_Builder1 = option_Builder0.type(class0);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArgs();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.desc("");
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(16);
      Option.Builder option_Builder2 = option_Builder1.optionalArg(true);
      assertSame(option_Builder2, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.required();
      option_Builder0.longOpt(" ]");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isRequired();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.argName("org.apache.commons.cli.ParseException");
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("org.apache.commons.cli.ParseException");
      Option option0 = option_Builder1.get();
      Converter<?, ?> converter0 = option0.getConverter();
      assertNotNull(converter0);
      
      option_Builder0.converter(converter0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }
}
